# Generated by Django 4.2.1 on 2023-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignature', models.CharField(max_length=10)),
                ('fecha', models.DateField(verbose_name='fecha')),
            ],
        ),
    ]
