# Generated by Django 4.2.1 on 2023-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_examen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='asignature',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='examen',
            name='date',
            field=models.TextField(max_length=11),
        ),
    ]
