# Generated by Django 4.2.6 on 2023-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_examen_asignature_alter_examen_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignatura', models.CharField(max_length=40)),
                ('tema', models.CharField(max_length=4)),
                ('text', models.TextField(max_length=10000)),
            ],
        ),
    ]
